AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template for creating Development Group and Policy'
Parameters:
  GroupName:
    Type: String
    Description: Enter Group Name.
Resources:
  Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
  Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: DenyPushMasterDevelopCodeCommit
      Groups:
        -  !Ref GroupName
      PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Deny
              Action:
                - 'codecommit:GitPush'
                - 'codecommit:DeleteBranch'
                - 'codecommit:PutFile'
                - 'codecommit:MergeBranchesByFastForward'
                - 'codecommit:MergeBranchesBySquash'
                - 'codecommit:MergeBranchesByThreeWay'
                - 'codecommit:MergePullRequestByFastForward'
                - 'codecommit:MergePullRequestBySquash'
                - 'codecommit:MergePullRequestByThreeWay'
              Resource: 'arn:aws:codecommit:eu-west-1:311134898078:*'
              Condition:
                StringEqualsIfExists:
                  'codecommit:References':
                    - refs/heads/master
                    - refs/heads/develop
                'Null':
                  'codecommit:References': false
