# Description: 'Template for creating Development user and attaching to a group'
# Parameters:
#   gitlabdnsHostedZodeId:
#     Type: String
#     Description: Enter HostedZoneId
Resources:
  machinedns:
     Type: AWS::Route53::RecordSet
     Properties:
       HostedZoneId : xxxxxxxxxxxxxx
       Name: vault.projectdevops.com
       ResourceRecords:
         - !GetAtt machine.PrivateIp
       TTL: '900'
       Type: A
     DependsOn:
        - machine
  machine:
     Type: AWS::EC2::Instance
     Properties:
       AvailabilityZone: eu-west-1a
       BlockDeviceMappings:
         -
           DeviceName: /dev/sda1
           Ebs:
             VolumeSize: 20
       ImageId: "ami-04facb3ed127a2eb6"
       InstanceType: "t2.medium"
       KeyName: adopsecurity
       SecurityGroupIds:
         - sg-xxxxxxxx
       SubnetId: subnet-xxxxxxxxxxx
       PrivateIpAddress: 10.x.x.x
       Tags:
         -
             Key: Name
             Value: mig-cicd-vault
       UserData:
           Fn::Base64: !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install wget zip bind-utils vim -y
            #install vault
            wget https://releases.hashicorp.com/vault/1.3.4/vault_1.3.4_linux_amd64.zip
            unzip vault_1.3.4_linux_amd64.zip
            chmod +x vault
            cp vault /usr/local/bin/
            vault -autocomplete-install


            #install consul
            wget https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_linux_amd64.zip
            unzip consul_1.7.2_linux_amd64.zip
            chmod +x consul
            cp consul /usr/local/bin/
            consul --version
            consul -autocomplete-install
            complete -C /usr/local/bin/consul consul
            sudo useradd --system --home /etc/consul.d --shell /bin/false consul
            sudo mkdir --parents /opt/consul
            sudo chown --recursive consul:consul /opt/consul
            cat <<EOT >> /etc/systemd/system/consul.service
            [Unit]
            Description="HashiCorp Consul - A service mesh solution"
            Documentation=https://www.consul.io/
            Requires=network-online.target
            After=network-online.target
            ConditionFileNotEmpty=/etc/consul.d/consul.hcl

            [Service]
            Type=notify
            User=consul
            Group=consul
            ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d/
            ExecReload=/usr/local/bin/consul reload
            KillMode=process
            Restart=on-failure
            LimitNOFILE=65536

            [Install]
            WantedBy=multi-user.target
            EOT

            sudo mkdir --parents /etc/consul.d
            sudo touch /etc/consul.d/consul.hcl
            sudo chown --recursive consul:consul /etc/consul.d
            sudo chmod 640 /etc/consul.d/consul.hcl
            cat <<EOT >> /etc/consul.d/consul.hcl
            datacenter = "aws"
            data_dir = "/opt/consul"
            encrypt = "Luj2FZWwlt8475wD1WtwUQ=="
            EOT

            sudo mkdir --parents /etc/consul.d
            sudo touch /etc/consul.d/server.hcl
            sudo chown --recursive consul:consul /etc/consul.d
            sudo chmod 640 /etc/consul.d/server.hcl
            cat <<EOT >> /etc/consul.d/server.hcl
            server = true
            bootstrap_expect = 1
            ui = true
            EOT
            sudo systemctl enable consul
            sudo systemctl start consul
            sudo systemctl status consul






Outputs:
  MachinePrivateIP:
    Value: !GetAtt machine.PrivateIp
  MachineURL:
    Value: !Ref machinedns
